# --- DATABASE CONFIG ---
db.url=jdbc:mysql://localhost:3306/auction_system?useSSL=false
db.user=root
db.password=

# --- SERVER CONFIG ---
server.port=8888
server.max_threads=100

# --- AUCTION RULES ---
auction.min_increment=10000

# --- ANTI-SNIPING (Nâng cao) ---
# N?u có ng??i ??t giá trong 60 giây cu?i cùng
auction.antisnipe.trigger_seconds=60
# Thì c?ng thêm 120 giây vào th?i gian k?t thúc
auction.antisnipe.extend_seconds=120