name: Backend CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Kéo source code mới nhất về
        uses: actions/checkout@v4

      - name: Cài đặt môi trường JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Chạy Test và Đóng gói
        working-directory: ./HeThongDauGia
        run: mvn -B clean package

      - name: Lưu giữ chiến lợi phẩm
        uses: actions/upload-artifact@v4
        with:
          name: hethongdaugia-server-jar
          path: HeThongDauGia/target/*.jar