import os
import json
import glob

project_root = r"E:\HeThongDauGia\HeThongDauGia"

# 1. Read README.md
readme_path = os.path.join(project_root, "README.md")
readme_content = ""
if os.path.exists(readme_path):
    with open(readme_path, "r", encoding="utf-8") as f:
        readme_content = f.read()[:3000]

# 2. Find entry point
entry_point = "src/main/java/org/example/ServerMain.java"

# 3. Read base system prompt
agents_dir = r"C:\Users\DELL\.gemini\config\plugins\agents"
with open(os.path.join(agents_dir, "tour-builder.md"), "r", encoding="utf-8") as f:
    sys_prompt = f.read()

sys_prompt += f"""

**Additional context from main session:**

Project README (first 3000 chars):
```
{readme_content}
```

Project entry point: {entry_point}

Use the README to align the tour narrative with the project's own documentation. Start the tour from the entry point if one was detected. The tour should tell the same story the README tells, but through the lens of actual code structure.

Language directive: Generate all textual content (summaries, descriptions, tags, titles, languageNotes, languageLesson) in vi. Maintain technical accuracy while using natural, native-level phrasing in the target language.
"""

with open(os.path.join(project_root, "tour_builder_sys_prompt.txt"), "w", encoding="utf-8") as f:
    f.write(sys_prompt)

# 4. Read graph data
with open(os.path.join(project_root, ".understand-anything", "intermediate", "assembled-graph.json"), "r", encoding="utf-8") as f:
    graph = json.load(f)

# Nodes (file-level only)
file_level_types = {'file', 'config', 'document', 'service', 'pipeline', 'table', 'schema', 'resource', 'endpoint'}
file_nodes = []
for n in graph.get("nodes", []):
    if n.get("type") in file_level_types:
        file_nodes.append({
            "id": n.get("id"),
            "name": n.get("name"),
            "filePath": n.get("filePath"),
            "summary": n.get("summary"),
            "type": n.get("type")
        })

# 5. The layers will be generated by phase 4, so this script should be run AFTER phase 4!
# Oh wait, we will just prepare the script, but I should read layers.json dynamically in the script when executed.
script_content = f"""
import json

graph_path = r"{os.path.join(project_root, '.understand-anything', 'intermediate', 'assembled-graph.json')}"
with open(graph_path, "r", encoding="utf-8") as f:
    graph = json.load(f)

edges = graph.get("edges", [])

layers_path = r"{os.path.join(project_root, '.understand-anything', 'intermediate', 'layers.json')}"
with open(layers_path, "r", encoding="utf-8") as f:
    layers_data = json.load(f)
    
if isinstance(layers_data, dict) and "layers" in layers_data:
    layers_data = layers_data["layers"]
    
layers_clean = []
for l in layers_data:
    layers_clean.append({{
        "id": l.get("id", ""),
        "name": l.get("name", ""),
        "description": l.get("description", "")
    }})

dispatch = f'''Create a guided learning tour for this codebase.
Project root: {project_root}
Write output to: {project_root}/.understand-anything/intermediate/tour.json
Project: HeThongDauGia - Không có mô tả nào được cung cấp cho dự án này.
Languages: css, fxml, java, json, mf, properties, txt, unknown, xml, yaml

Nodes (all file-level nodes):
```json
{json.dumps(file_nodes, indent=2)}
```

Layers:
```json
{{json.dumps(layers_clean, indent=2)}}
```

Edges (all types):
```json
{{json.dumps(edges, indent=2)}}
```
'''

with open(r"{os.path.join(project_root, 'tour_builder_dispatch.txt')}", "w", encoding="utf-8") as f:
    f.write(dispatch)
"""

with open(os.path.join(project_root, "generate_phase5.py"), "w", encoding="utf-8") as f:
    f.write(script_content)
